name: makefile

on:
  push:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    #- name: configure
    #  run: ./configure
      
    - name: Install dependencies
      run: make
